### PR TITLE
fix sftp ls() method from root

### PR DESCRIPTION
**Pull request by matteosantama**
See comments in #759

### CODE REVIEW

**Comment by matteosantama** [comment]
Tests are failing because with this sftp server, paramiko does not let you create paths that start with a `/`. Given that `SFTPFileSystem.root_marker == ""`, this seems reasonable to me.

**Comment by martindurant** [comment]
So what do you suppose we should do?

**Comment by martindurant** [comment]
Yeah, sorry, still a bit confused here. The test you add to show the problem doesn't actually run, and other things are failing which don't seem to have changed.

Weren't you thinking of changing the condition mentioned in #759 to `is not None`?

**Comment by matteosantama** [comment]
There are a few things to resolve. First, the test I added is failing with `fixture 'sftp_server' not found`. How can I add the `mocksftp` to the testing environment? 

Here's the problem, when I simply make it `is not None:`, I get 

```python
fs.touch("a.txt")
assert fs.ls(fs.root_marker) == ["/a.txt"]
```
to pass. However, if I instead run `fs.touch("/a.txt")`, I get a `PermissionError`. `paramiko` does not like the leading slash. 

Now to be honest, I'm not sure if this is a just quirk of my mock SFTP server. This same problem is what's breaking the old `sftp` tests. So the question is, should  SFTP paths start with a leading slash, or not?

**Comment by martindurant** [comment]
> So the question is, should SFTP paths start with a leading slash, or not?

I don't think it matters too much, so long as we are consistent. I am happy to go with what paramiko does, apparently not allowing a leading "/". Of course, the paths the user can pass and the paths reported back by the implementation should match too.

**Pull request closed without merging**
