### PR TITLE
Support append mode for ArrowFSWrapper

### PR DESCRIPTION
**Pull request by leoleoasd**
This PR adds support append mode for ArrowFSWrapper.

https://github.com/apache/arrow/blob/apache-arrow-1.0.0/python/pyarrow/_fs.pyx#L673

It seems that from v1.0.0, pyarrow supports `open_append_stream`.

### CODE REVIEW

**Comment by martindurant** [comment]
Can we please add a test for this in test_arrow.py?

**Comment by leoleoasd** [comment]
Hi, I've added tests. Works fine in my repo (https://github.com/leoleoasd/filesystem_spec/actions/runs/3346115981), but I need approval for running tests in PR.
image

**Comment by leoleoasd** [comment]
Hi, I would like to ask when will we release this into PyPI, is there an ETA? 
Since our cluster only supports installing packages from PyPI, I need to apply a patch into `site-packages` every time I submit a new job before the release.

**Comment by martindurant** [comment]
We have a few things coming in now, so maybe within the next week.

**Pull request merged**
