### PR TITLE
Allow batches in more async operations

### PR DESCRIPTION
**Pull request by martindurant**

### CODE REVIEW

**Comment by martindurant** [comment]
cc @rabernat

**Comment by martindurant** [comment]
The problem is that the keyword "batch_size" is not in the non-async implementations. We could include it there in all the calls, but ignore it. If users only ever touch the default value, this is not an issue.

**Comment by rabernat** [comment]
I like the idea of setting this via global configuration options for fsspec. That would seem to be easier than passing config options through every function.

**Comment by martindurant** [comment]
Here we enable both (but needs documentation, of course). The variables `fsspec.asyn._DEFAULT_BATCH_SIZE` and `fsspec.asyn._NOFILES_DEFAULT_BATCH_SIZE` and corresponding config keys "gather_batch_size", "nofiles_gather_batch_size" (config takes precedence, if key exists; function kwargs take ultimate precedence).

**Comment by martindurant** [comment]
(thank you, CI, for spotting the subtle bug!)

**Pull request merged**
