### PR TITLE
callbacks: forward tqdm args

### PR DESCRIPTION
**Pull request by Timost**
follow-up to #931

### CODE REVIEW

**Comment by martindurant** [comment]
I wonder if there's a decent way to test this with pytest's capture? Probably we could test instead by mocking tqdm completely (i.e., nothing is actually printed).

**Comment by Timost** [comment]
Yeah both mocking and using [capfd](https://pytest.org/en/latest/reference/reference.html#std-fixture-capfd) would work I guess.
I can give it a try.

**Comment by martindurant** [comment]
(please ping me when you've had a go, or perhaps if you've realised you won't have time to work on the mock)

**Comment by Timost** [comment]
Here is a version using `capsys`. It's probably really brittle (wouldn't be surprised if the ci failed).
Using mock would probably be safer, what do you think ?

**Comment by martindurant** [comment]
It does seem like, as written, the exact output might depend on the assumed console width and character encoding, so I would expect this to fail on some systems. Also, I was wondering where the iterations between the first and last end up. I'm not certain whether this can be hardened, so if mocking is easy, that will do.

**Comment by Timost** [comment]
I think tqdm buffers the output based on the rate of processing, so in this case it only outputs the first and last "frames" of the progress bar.
I'll try an alternative based on mocks.

**Comment by Timost** [comment]
Here you go ! I should have gone with mocks directly '^^.

**Comment by martindurant** [comment]
Perfect

**Pull request merged**
