### PR TITLE
Add dependencies for building docs

### PR DESCRIPTION
**Pull request by DarkLight1337**
I found that I couldn't build the documentation just from installing `dev` and `test` dependencies. It turns out that `pyproject.toml` currently does not specify the dependencies for building the documentation.

This PR adds the `doc` extra which includes such dependencies, making it easier to set up the environment for building documentation.

### CODE REVIEW

**Comment by martindurant** [comment]
This essentially replicates the environment in https://github.com/fsspec/filesystem_spec/blob/master/docs/environment.yml . It seems like a bad idea to have the environment in two places.

**Comment by DarkLight1337** [comment]
> This essentially replicates the environment in https://github.com/fsspec/filesystem_spec/blob/master/docs/environment.yml . It seems like a bad idea to have the environment in two places.

I have addressed this in the latest commit.

**Comment by martindurant** [comment]
```
  - (b'{"key": "value"}')
  ?           -
  + (b'{"key":"value"}')
```
Apparently the JSON serialization changed format slightly

**Comment by DarkLight1337** [comment]
> ```
>   - (b'{"key": "value"}')
>   ?           -
>   + (b'{"key":"value"}')
> ```
> 
> Apparently the JSON serialization changed format slightly

Seems that this was introduced by #1562. Imo we should fix that in a separate PR.

**Comment by martindurant** [comment]
The tests passed at the time, so some version got updated. Since it's a one-character fix, I'd be happy to see it here.

**Comment by DarkLight1337** [comment]
> The tests passed at the time, so some version got updated. Since it's a one-character fix, I'd be happy to see it here.

The problem is not that trivial. Seems that the separator in `json.dumps` depends on whether `json` or `ujson` is being used to serialize the data.

**Comment by martindurant** [comment]
It's find to importorskip("ujson") for the test, and we know that the package will be there in CI.

**Comment by DarkLight1337** [comment]
> It's find to importorskip("ujson") for the test, and we know that the package will be there in CI.

I found a better solution, which is to use the same json module to encode the dictionary for the reference value.

**Pull request merged**
