### PR TITLE
Bugfix dbfs read by range

### PR DESCRIPTION
**Pull request by tomerm-iguazio**
Reading a dbfs file should start from start value - not from 0.

### CODE REVIEW

**Comment by martindurant** [comment]
Could we make some tests for this, please?

**Comment by tomerm-iguazio** [comment]
Test added.

**Comment by martindurant** [comment]
Do you know how to make a VCR recording?

**Comment by tomerm-iguazio** [comment]
please run again...

**Comment by tomerm-iguazio** [comment]
fixed

**Pull request merged**
