### PR TITLE
Correct ls() for parquet backed nested reference sets

### PR DESCRIPTION
**Pull request by martindurant**
Fixes https://github.com/fsspec/kerchunk/issues/474

@sreesanjeevkg , can you test, please?

### CODE REVIEW

**Comment by sreesanjeevkg** [comment]
@martindurant , how do I install the changes from your branch for testing ? 

[martindurant:ref_nested_ls_parq](https://github.com/martindurant/filesystem_spec/tree/ref_nested_ls_parq)

**Comment by martindurant** [comment]
I think
```bash
> pip install git+https://github.com/martindurant/filesystem_spec.git@ref_nested_ls_parq
```

**Comment by sreesanjeevkg** [comment]
Hey Martin, I am able to access the file from parquet. Thank you for your help and quick turnaround.

Screenshot 2024-07-08 at 12 37 30 PM

**Comment by martindurant** [comment]
A simpler line to open the data:
```
ds = xr.open_dataset("combined.parq", engine="kerchunk", chunks="auto", group="Solar_Zenith")
```

**Pull request merged**
