### PR TITLE
 Fix #954: don't crash when reading empty file from libarchive 

### LINKED ISSUE #954: libarchive filesysystem breaks on empty files
When given a tar file with an empty file inside, libarchive explodes if you try to open the empty file:

```python
import os
import fsspec
import tarfile
import tempfile
from io import BytesIO
td = tempfile.TemporaryDirectory()
LibArchive = fsspec.get_filesystem_class("libarchive")

# tar file created this way is fine
with tarfile.TarFile.open(f"{td.name}/empty.tar.gz", mode="w:gz") as tf:
    # create an empty file and add it to the archive
    io = BytesIO()
    io.write(b"")
    tf.addfile(tarfile.TarInfo("empty.txt"), io)

# extract tarball using TarFile to show it's fine
with tarfile.TarFile.open(f"{td.name}/empty.tar.gz", mode="r:gz") as tf:
    os.chdir(td.name)
    tf.extractall(td.name)
    assert "empty.txt" in os.listdir(td.name)

# now try to read the file with fsspec/libarchive:
f = LibArchive(f"{td.name}/empty.tar.gz").open("empty.txt")
```

fails with:

```
Traceback (most recent call last):
  File "/Users/dlwh/src/sprucfluo/examples/stream_lambada.py", line 45, in <module>
    f = LibArchive(f"{td.name}/empty.tar.gz").open("empty.txt")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sprucfluo/lib/python3.10/site-packages/fsspec/spec.py", line 1009, in open
    f = self._open(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/sprucfluo/lib/python3.10/site-packages/fsspec/implementations/libarchive.py", line 209, in _open
    raise ValueError
ValueError
```

The relevant code is here:

```
    def _open(
        self,
        path,
        mode="rb",
        block_size=None,
        autocommit=True,
        cache_options=None,
        **kwargs,
    ):
        path = self._strip_protocol(path)
        if mode != "rb":
            raise NotImplementedError

        data = bytes()
        with self._open_archive() as arc:
            for entry in arc:
                if entry.pathname != path:
                    continue
                for block in entry.get_blocks(entry.size):
                    data = block
                    break
                else:
                    raise ValueError
        return MemoryFile(fs=self, path=path, data=data)
```

I think it's as simple as checking if `entry.size == 0` and being happy to return an empty data.

### PR DESCRIPTION
**Pull request by dlwh**
As above, added a simple unit test and verified it crashes without the patch

### CODE REVIEW

**Comment by martindurant** [comment]
Please run pre commit hooks to appease the linter - otherwise looks good.

**Comment by dlwh** [comment]
I'm a bit confused... I don't see a pre-commit hook? Happy to lint of course.

```
~/src/filesystem_spec (master)$ ls .git/hooks
applypatch-msg.sample		post-update.sample		pre-merge-commit.sample		pre-receive.sample		update.sample
commit-msg.sample		pre-applypatch.sample		pre-push.sample			prepare-commit-msg.sample
fsmonitor-watchman.sample	pre-commit.sample		pre-rebase.sample		push-to-checkout.sample
~/src/filesystem_spec (master)$
```

**Comment by martindurant** [comment]
You would run
```
pre-commit install
```
but just fixing the whitespace as shown in https://github.com/fsspec/filesystem_spec/runs/6229522463?check_suite_focus=true#step:4:73 would do fine.

**Comment by dlwh** [comment]
ah i see, it's a special package, not a git precommit hook.

**Comment by martindurant** [comment]
The effect of running that is to install pre commit hooks locally :)

**Comment by dlwh** [comment]
ah, ok, thanks! sorry i'm still pretty noob-ish in the python ecosystem.

**Pull request merged**
