### PR TITLE
Make glob only read relevant paths

### PR DESCRIPTION
**Pull request by drorspei**
Hi!

This is to resolve issue #727 that I opened.

The code here is copied from CPython's pathlib glob implementation. I don't know anything about licenses, and don't know if the work needs to be attributed somehow somewhere in the code.

### CODE REVIEW

**Comment by martindurant** [comment]
First running the tests to see if your method works :) 
Then we can talk about whether this is a reasonable thing to do.

**Comment by drorspei** [comment]
Cool cool

I see some tests indeed fail. I didn't run the full suite for lack of docker setup on my laptop; I'll get a beefier machine and make sure these pass as well.

Note that there are inconsistencies in what is expected from glob, shown in these test failures. Specifically, my version returns exactly what is returned from ls, but it's not clear which calls are expected to return the beginning front slash and which don't.

**Comment by martindurant** [comment]
I believe for HDFS, paths should always start with `"/"`. Perhaps the implementation is missing `root_marker = "/"` as a class attribute.

**Comment by drorspei** [comment]
Cool. I'm actually having trouble running the hdfs tests locally, trying to resolve ^_^

Do you know if I need any extra configuration for any of these tests?

In the ftp implementation, using `ls(path, detail=True)` will return results with the root marker, and using `ls(path, detail=False)` will return without. To make it compatible, I'll update the pull request to only use `detail=True` in all calls to `ls`.

**Comment by martindurant** [comment]
> To make it compatible, I'll update the pull request to only use detail=True

Better would be to fix it!

At this point, I hope that other people chime in here about the general idea of this PR (but it is Friday, so this might take a while). In the general case, skipping `ls` on directories that we know aren't required - as would be done by default find/walk - seems like a good idea. I would at this point probably put all the relevant code in a separate module and indeed include whatever license/notice requirements. Also worth mentioning, is that the current `glob` is derived from python's builtin `glob.glob` and why pathlib's `glob` is different. 

Note that some backends (s3, ...) can do `find` with a single call, instead of the potentially many calls to walk a directory, so they should *not* be changed. For them, it will almost always be much faster with `find`. It should be checked what happens is some sub-tree is permission locked (I reckon nothing, they just won't show up).

**Comment by drorspei** [comment]
Huh, I'm actually doing all of this because my queries to S3 are slow, and this pull request reduces my call times by more than x10.

The implementation in s3fs is a bit complicated, it's far from a single call. First, if there's no "**" in the path, then it is in fact many calls to `walk`. Second, if there is a "**" in the path, the performance will depend on how many objects are in the directory that do not match the pattern: if a small amount, then sure, the call to `list_objects_v2` with pagination will be fast. But if there are many objects, as I have, then again it is much slower. I'm not sure if pagination is considered "a single call", but as far as the network layer goes it's definitely not.

I've changed the code to pass the (s)ftp and cache tests. I still need to configure hdfs locally somehow to test that, do you maybe have a reference for this?

**Comment by drorspei** [comment]
Hej hej!

Ok! I thought a bit more, tell me what you think about the following change to the code and whether you think it will fit well with s3fs as well as other systems: find the first "\*\*" in the pattern, and use the new "selectors" for everything up to the "\*\*" - meaning only precise matches and using `fs.ls` for "\*". Then from the "\*\*" use exactly a single call to `fs.find` as it is in the current implementation of `glob`. This way patterns without "\*\*" benefit from reading only relevant directories, and those with it call `list_objects_v2` only the part of the path that needs it, so a pattern like `year=*/month=01/**/*.csv` won't get x12 objects to match over (which is similar to the data I'm dealing with daily).

I think this is definitely better than the current pull request, and for some use cases it's better than the current fsspec implementation, though not all. For example, continuing with my example above of `year=*/month=01/**/*.csv`, if there is only the single "month=01" in all the "years=*", then a single call to `find` is better than a call to `ls` and then multiple find calls.

We can also play with the design and let users have a choice.

What do you think?

**Comment by drorspei** [comment]
Hej hej
Sorry, I don't have enough time to push this. Maybe some time in the future ^_^

**Pull request closed without merging**
