### PR TITLE
Add `wandbfs` registry for `wandbfsspec`

### PR DESCRIPTION
**Pull request by alvarobartt**
As you may know, there's already a `wandb` implementation of `fsspec` available, but it's no longer maintained as I contacted the author @/jkulhanek via email and he told me that he's no longer maintaining it. `wandbfs` available at https://github.com/jkulhanek/wandbfs

I realized there was another Python package for `wandb`'s fsspec implementation once I was in the later development stages of `wandbfsspec`, that's the reason why I created another Python package. Find the `wandbfsspec` repository at https://github.com/alvarobartt/wandbfsspec, and the v0.1.0 released published on PyPI at https://pypi.org/project/wandbfsspec/

Besides the fact that `wandbfsspec` contains more functionality implemented than `wandbfs`, I'm also planning to add an interface for the [WandB Artifact Store](https://docs.wandb.ai/guides/artifacts) so as to support both "file systems" available in `wandb`.

Note that this is relevant, as `fsspec` makes everything easy providing a common interface to access different storage systems and some packages such as [zenml](https://github.com/zenml-io/zenml) that aim to build portable MLOps solutions, use these interfaces so as to allow the user to easily change the steps of their pipelines. This can also be extended to data pipelines, model pipelines, etc.

So on, I find this new implementation useful and I'm planning to actively maintain it, and start developing some integrations of both `wandb` file system and artifact store, for some packages based on `fsspec` components.

### CODE REVIEW

**Comment by martindurant** [comment]
@jkulhanek , do you approve the use of this newer implementation over your own?

**Comment by jkulhanek** [comment]
I want to clarify that I still maintain my wandbfs implementation and I am not aware of stating otherwise. I am still responding to any issues and feature requests regarding the project and I am accepting PRs.

I do not think publishing a new package to replace the current one is a wise idea. This would be a bad experience for users of the current package. If @alvarobartt was missing something, he/she/they should have opened an issue at my repo, and I would have been be glad to help. In my email to @alvarobartt I offered the role of collaborator for the project. @alvarobartt, why can't you do the required changes to the current project?

I didn't know that there was any demand for the implementation of the wandb artifacts API. I can implement it in my package - it is just a couple of lines of code. @alvarobartt, what other functionality are you missing from my package?

Ultimately it is @martindurant decision. If you chose the new alternative implementation I can put a disclaimer notice to my repo that there is a new preferred implementation.

**Comment by alvarobartt** [comment]
Yes sorry, I didn't put it properly into words now that I re-read that email. Sorry for the confusion from my side @jkulhanek.

So the thing here was not to replace it, but to create an alternate version, as the idea is to also cover the WandB Artifact Store, not just the File System.

And obviously yours is working fine is just that I didn't realize  before starting the development of mine that's why I renamed the registry to wandbfs rather than just wandb in order to avoid issues. So we can wait for this to be addressed as I'm not in a hurry just testing different stuff.

P.S. the artifact store implementation was not a demand from anyone, just something I wanted to test as it's being useful for me. I also took the chance to submit some PRs to wandb to fix some issues I found while creating my own implementation. Anyway, since there's no need to merge this PR, you can just keep your wandb registry @jkulhanek, sorry for the misunderstanding, I just thought that different packages could co-exist.

**Comment by jkulhanek** [comment]
@alvarobartt, I would like it very much for us to collaborate on the wandbfs project if you like. You can submit the artifact API implementation there if you like. What do you think?

Both packages can definitely coexist. However, I think registering both packages under similar names might confuse the users.

**Comment by alvarobartt** [comment]
Sure I'll do that once I explore it further as my code for that is still on a private branch and immature to be published, but for sure we can look for the best way to put everything together!

**Comment by martindurant** [comment]
I am sorry to have started a disagreement!
I must confess to being ignorant of either implementation's code or indeed the general use case. I hope the discussion here is fruitful and you reach consensus.

I do agree that it is a good goal to reduce user experience changes and confusion as much as possible.

**Comment by alvarobartt** [comment]
Hi, @martindurant no worries! We can close this PR already!

**Pull request closed without merging**
