### PR TITLE
Add session_cert and session_verify parameters to WebHDFS class (enables mTLS)

### PR DESCRIPTION
**Pull request by markhatch**
Provides mechanism to supply certificates in the WebHDFS session.

### CODE REVIEW

**Comment by martindurant** [comment]
I feel like this could be done simpler with optional kwargs to the existing webHDFS rather than making a new class. Since fsspec keys URLs by their protocol prefixes, this would ensure that "webhdfs" would serve both uses, but allow for the extra arguments to be defined in config.

**Comment by markhatch** [comment]
> I feel like this could be done simpler with optional kwargs to the existing webHDFS rather than making a new class. Since fsspec keys URLs by their protocol prefixes, this would ensure that "webhdfs" would serve both uses, but allow for the extra arguments to be defined in config.

Sounds good, I'll take a stab at that!

**Comment by martindurant** [comment]
(please ping me when you want another look)

**Comment by markhatch** [comment]
Had to add #noqa to the url line on 105 to pass pre-commit, error didn't make sense to me (and I didn't change the line)

```
fsspec/implementations/webhdfs.py:105:56: E231 missing whitespace after ':'
fsspec/implementations/webhdfs.py:105:65: E231 missing whitespace after ':'
```

**Comment by markhatch** [comment]
@martindurant think the changes are ready. Initially thought I could just pass `session_kwargs` through, but guess that requests.Session doesn't have init kwargs so used explicit parameters instead.

**Pull request merged**
