### PR TITLE
xrootd to root typo

### PR DESCRIPTION
**Pull request by ScottDemarest**
mis typed protocol name for fsspec implementation

### CODE REVIEW

**Comment by martindurant** [comment]
Is this how xrootd connections are usually written? I have a slight worry that "root filesystem" might get misunderstood.

**Comment by ScottDemarest** [comment]
i agree it's a confusing protocol name, but that is what it is. 
for example: root://eospublic.cern.ch/...

**Comment by ScottDemarest** [comment]
Perhaps I should add some more detail to the error message to clear that up?

**Comment by martindurant** [comment]
Yes, that seems like a good idea. More information is always good.

**Pull request merged**
