### PR TITLE
Change local rm to throw an expressive error

### PR DESCRIPTION
**Pull request by haim0n**
Inform the user when he forgets to add a "recursive" flag to directory path removal.

### CODE REVIEW

**Comment by martindurant** [comment]
Do you mind adding or modifying a test to trigger the extra code?

**Comment by haim0n** [comment]
Sure - done

**Comment by martindurant** [comment]
Please let me know when you have dealt with the lint

**Comment by haim0n** [comment]
> Please let me know when you have dealt with the lint

@martindurant , done.

**Pull request merged**
