### PR TITLE
Fix broken azure blob storage paths

### LINKED ISSUE #1002: Broken `abfs://` on version 2022.7.0
I'm running the following code to access an Azure blob storage container:
```python
import adlfs
fs = adlfs.AzureBlobFileSystem()
fs.ls("abfs://my-container-name")
```

This works perfectly with `fsspec==2022.5.0` and `adlfs==2022.7.0`.  However with  `fsspec==2022.7.0` and `adlfs==2022.7.0` I get `FileNotFoundError` arising from `azure.core.exceptions.ResourceNotFoundError: The specified container does not exist.`. It does work, however, if I run:
```python
fs.ls("az://my-container-name")
```

**Expectation:** `abfs://...` syntax should be supported on Python environments containing `fsspec==2022.7.0`.

**Environment:**
* Platform: Ubuntu Linux
* Python: 3.9
* Credentials provided using `AZURE_STORAGE_CONNECTION_STRING` environment variable.

Working Python environment (from `pip freeze`):
```
adal==1.2.7
adlfs==2022.7.0
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
azure-core==1.24.2
azure-datalake-store==0.0.52
azure-identity==1.10.0
azure-storage-blob==12.13.0
certifi @ file:///opt/conda/conda-bld/certifi_1655968806487/work/certifi
cffi==1.15.1
charset-normalizer==2.1.0
cryptography==37.0.4
frozenlist==1.3.0
fsspec==2022.5.0
idna==3.3
isodate==0.6.1
msal==1.18.0
msal-extensions==1.0.0
msrest==0.7.1
multidict==6.0.2
oauthlib==3.2.0
portalocker==2.5.1
pycparser==2.21
PyJWT==2.4.0
python-dateutil==2.8.2
requests==2.28.1
requests-oauthlib==1.3.1
six==1.16.0
treelite==2.0.0
treelite-runtime==2.0.0
typing_extensions==4.3.0
urllib3==1.26.11
yarl==1.7.2
```

Broken Python environment:
```
adal==1.2.7
adlfs==2022.7.0
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
azure-core==1.24.2
azure-datalake-store==0.0.52
azure-identity==1.10.0
azure-storage-blob==12.13.0
certifi @ file:///opt/conda/conda-bld/certifi_1655968806487/work/certifi
cffi==1.15.1
charset-normalizer==2.1.0
cryptography==37.0.4
frozenlist==1.3.0
fsspec==2022.7.0
idna==3.3
isodate==0.6.1
msal==1.18.0
msal-extensions==1.0.0
msrest==0.7.1
multidict==6.0.2
oauthlib==3.2.0
portalocker==2.5.1
pycparser==2.21
PyJWT==2.4.0
python-dateutil==2.8.2
requests==2.28.1
requests-oauthlib==1.3.1
six==1.16.0
treelite==2.0.0
treelite-runtime==2.0.0
typing_extensions==4.3.0
urllib3==1.26.11
yarl==1.7.2
```

### PR DESCRIPTION
**Pull request by toby-coleman**
Fixes #1002 by reverting the changes made in #988

### CODE REVIEW

**Comment by martindurant** [comment]
@toby-coleman , do you think this is reason enough to need a new release, even while one is just on its way out the door?

**Comment by toby-coleman** [comment]
Not sure how heavily used blob storage path are, but this was enough to break the package I'm working on. Would prefer an earlier release if possible, but I can work around it in the immediate term by pinning the `fsspec` version.

**Comment by gbmarc1** [comment]
Yeah took me a while to figure out why my program broke also.

**Comment by hannahker** [comment]
Same here! Thanks a lot for the fix!

**Pull request merged**
