### PR TITLE
Add encoded keyword for the HTTPFileSystem

### PR DESCRIPTION
**Pull request by mraspaud**
This PR adds the `encoded` keyword argument to `HTTPFileSystem` to allow ready-encoded urls to be passed unaltered.

The rationale behind this is that aiohttp, by using yarl, canonizes the urls before using them in `.get`. This works for most servers, as they are compliant with, among others, RFC3986. However, some servers, in particular the one following the OpenAPI specification, do not comply, hence making a mess for example when sending a url containing `:` in the path part.
To prevent the canonization of the url, aiohttp recommends [here](https://docs.aiohttp.org/en/stable/client_quickstart.html#passing-parameters-in-urls) passing `encoded=True` to the `yarl.URL` object creation before passing it to aiohttp's `get`. More details and examples can be provided upon request.

This PR hence adds the possibility to configure the HTTPFileSystem to bypass the canonization of the urls.

### CODE REVIEW

**Comment by mraspaud** [comment]
PS: hints on how to test this would be welcome.

**Comment by martindurant** [comment]
To test, I suppose you would need the server (fsspec.tests.HTTTestHandler) to simply respond back with the full path that was requested, where this mode is activated by passing a special header keyword.

**Comment by martindurant** [comment]
Do you expect to be able to make a test like I suggested?

**Comment by martindurant** [comment]
Please check that the test I added makes sense to you.

**Comment by mraspaud** [comment]
@martindurant thanks a lot for adding the test! I've been travelling those last weeks, so I didn't have time to look at this before today. But it looks good, I just added a “:“ character as that was the one I was struggling with. So all good for me now!

**Pull request merged**
